name: build musl

on:
  workflow_dispatch:

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git clone https://github.com/egorsmkv/russh
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add x86_64-unknown-linux-musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build
        run: |
          cd russh
          cargo build --release --target x86_64-unknown-linux-musl --example client_exec_interactive

      - name: Check
        run: ls -lh

      - name: Rename
        run: cp russh/target/x86_64-unknown-linux-musl/examples/client_exec_interactive russh/russh_client

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: russh_client-linux-musl
          path: russh/russh_client
