name: build

on:
  workflow_dispatch:

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: git clone https://github.com/Eugeny/russh
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cd russh
          cargo build --release --example client_exec_interactive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: target_results
          path: target/
